INSERT INTO "public"."education" ("id", "hero_heading", "hero_subheading", "hero_description_1", "hero_description_2", "hero_image_url", "who_heading", "who_descriptions", "help_heading", "help_description", "help_items", "approach_heading", "approach_paragraphs", "outcome_heading", "outcome_paragraphs", "why_me_heading", "why_me_paragraphs", "why_me_image_url", "contact_heading", "contact_description", "contact_button_text", "contact_note", "created_at", "updated_at", "expect_heading") VALUES ('d9a2b4ae-2b7c-41f5-81ad-72a1fda9130b', 'Education for the hair industry, built from real experience.', 'For employed stylists, self-employed stylists, managers and salon business owners who want more confidence, stronger leadership and a career or business that feels sustainable', 'You might still love the industry, but not the way you’re living inside it.

Maybe you feel burnt out, disillusioned, constantly under pressure, or like the career you once wanted no longer feels the way you thought it would.

You may be questioning your role, your business, your confidence, or what you even want next.

After more than 25 years in the hair industry — building salons, leading teams, growing businesses and navigating major change myself — I know how easy it is to keep pushing while quietly losing the joy in it.', 'This education is for the moments when you know something needs to change, but you’re not yet sure what.

It’s about helping you get clear, rebuild confidence, lead and work in a way that feels more sustainable, and create a career or business that still leaves room for you.

Because success shouldn’t just look good from the outside.

It should feel good to live.', 'https://mfenauruirpaqfynbugx.supabase.co/storage/v1/object/public/images/education/IMG_4042-84086b37-110d-4e0d-953a-fb7c2aaac759.jpeg', 'Who This Is For', '["For salon owners and stylists who want to feel more confident, more consistent and more in control of what they''re doing.", "Whether that''s improving your skills, strengthening your team or creating a better client experience, this is built around real salon life — not theory.", "Whether you''re just starting out or have years of experience, if you know there''s more you could be doing — this is just right for you."]', 'What I Can Help With', 'This can be tailored depending on what you need, but often includes:', '["Building confidence behind the chair", "Refining cutting, colour and finishing work", "Improving consultations and client connection", "Raising standards across a team", "Creating a better overall client experience", "Supporting salon owners with team and business development"]', 'My Approach', '["I don''t believe in one-size-fits-all training.", "Everything I offer is personal, honest and based on real experience — what actually works in a busy salon, day in and day out."]', 'The Outcome', '["The goal is simple — to help you feel more confident, more capable and clearer in what you''re doing.", "That might show up in your work, your clients, your team or your business as a whole."]', 'Why Work With Me', '["I''ve experienced the industry from every angle — as a stylist, salon owner and mentor.", "Having built, grown and sold a successful salon, I understand both the creative and business side of this industry, and that''s what I now bring into the way I support others."]', '/assets/images/VBC - Salon.jpg', 'Get In Touch', 'If you''re ready to improve your skills, your team or your business, I''d love to hear from you.', 'Enquire about education', 'Introductory rates available for first bookings', '2026-04-09 22:40:35.815888+00', '2026-09-15 14:59:19.961719+00', 'What You Can Expect');